import { strict as assert } from 'node:assert'
import { ENEMY_IDS, VERTICAL_ESCAPE_CHECKPOINTS, useGameStore } from '../src/store/useGameStore.js'

const state = () => useGameStore.getState()

state().setStatus('ready')
assert.equal(state().openReleasePanel('showcase'), true)
assert.equal(state().systemPanel, 'showcase')
assert.deepEqual(state().panelHistory, [])
assert.equal(state().openReleasePanel('credits'), true)
assert.equal(state().systemPanel, 'credits')
assert.deepEqual(state().panelHistory, ['showcase'])
state().closeReleasePanel()
assert.equal(state().systemPanel, 'showcase')
state().closeReleasePanel()
assert.equal(state().systemPanel, null)
assert.equal(state().status, 'ready')

// Phase 8 overhauled vertical slice.
state().startProtocol('vertical')
assert.equal(state().gameMode, 'vertical')
assert.equal(state().verticalStage, 0)
assert.equal(state().storyModal, 'transmission')
state().interactWithStory()
state().setInput('forward', true)
state().setInput('forward', false)
state().setInput('sprint', true)
state().setInput('sprint', false)
assert.equal(state().verticalTutorial.moved, true)
assert.equal(state().verticalTutorial.sprinted, true)

const verticalRelay = state().storyTerminals.find((terminal) => terminal.id === 'relay-alpha')
state().setNearbyTerminal(verticalRelay)
assert.equal(state().interactWithStory(), true)
assert.equal(state().storyModal, 'hack')
state().submitHackNode(1)
assert.equal(state().hackAttempts, 1)
for (const node of [2, 4, 1, 3]) state().submitHackNode(node)
assert.equal(state().verticalStage, 1)
state().interactWithStory()
assert.equal(state().requestAttack(), true)
assert.equal(state().verticalTutorial.attacked, true)
for (const id of ['striker-01', 'striker-02']) assert.equal(state().damageEnemy(id, 999), true)
assert.equal(state().verticalWave, 1)
assert.equal(state().advanceVerticalWave(), true)
assert.equal(state().verticalWave, 2)
for (const id of ['disc-guard-01', 'defender-01', 'hunter-01']) assert.equal(state().damageEnemy(id, 999), true)
assert.equal(state().advanceVerticalWave(), true)
assert.equal(state().verticalWave, 3)
assert.equal(state().damageEnemy('commander-01', 999), true)
assert.equal(state().verticalStage, 2)
assert.equal(state().storyModal, 'transmission')
state().interactWithStory()
assert.equal(state().verticalMounted, true)
state().setInput('sprint', true)
state().setInput('sprint', false)
state().setInput('drift', true)
state().setInput('drift', false)
assert.equal(state().verticalTutorial.boosted, true)
assert.equal(state().verticalTutorial.drifted, true)
state().setVerticalTime(31.25)
for (let index = 0; index < VERTICAL_ESCAPE_CHECKPOINTS.length; index += 1) {
  assert.equal(state().passVerticalCheckpoint(index), true)
}
assert.equal(state().status, 'mission_complete')
assert.equal(state().verticalStage, 3)

state().returnToProtocolSelect()
assert.equal(state().status, 'ready')

// Presentation, settings, and photo-mode regressions.
state().startProtocol('story')
assert.equal(state().gameMode, 'story')
assert.equal(state().storyStage, 0)
assert.equal(state().storyModal, 'transmission')
assert.equal(state().audioUnlocked, true)
assert.deepEqual(state().panelHistory, [])

assert.equal(state().togglePause(), true)
assert.equal(state().status, 'paused')
assert.equal(state().systemPanel, 'pause')
state().openReleasePanel('capture')
assert.equal(state().systemPanel, 'capture')
assert.deepEqual(state().panelHistory, ['pause'])
state().closeReleasePanel()
assert.equal(state().systemPanel, 'pause')

state().openSettings()
assert.equal(state().systemPanel, 'settings')
assert.equal(state().returnPanel, 'pause')
assert.equal(state().setPreference('screenShake', false), true)
assert.equal(state().screenShake, false)
state().closeSettings()
assert.equal(state().systemPanel, 'pause')
state().resumeGame()
assert.equal(state().status, 'running')

assert.equal(state().enterPhotoMode(), true)
assert.equal(state().status, 'paused')
assert.equal(state().systemPanel, 'photo')
const captureSerial = state().screenshotSerial
state().requestScreenshot()
assert.equal(state().screenshotSerial, captureSerial + 1)
state().exitPhotoMode()
assert.equal(state().status, 'running')

state().setQuality('high')
state().setAutoQuality(true)
for (let i = 0; i < 5; i += 1) state().setFps(30)
assert.equal(state().quality, 'medium')
for (let i = 0; i < 24; i += 1) state().setFps(60)
assert.equal(state().quality, 'high')

// Legacy story regression.
state().interactWithStory()
const relay = state().storyTerminals.find((terminal) => terminal.id === 'relay-alpha')
state().setNearbyTerminal(relay)
assert.equal(state().interactWithStory(), true)
for (const node of [2, 4, 1, 3]) state().submitHackNode(node)
assert.equal(state().storyStage, 1)
state().interactWithStory()
for (const id of ['archive-echo', 'archive-lyra']) {
  const terminal = state().storyTerminals.find((item) => item.id === id)
  state().setNearbyTerminal(terminal)
  assert.equal(state().interactWithStory(), true)
  state().interactWithStory()
}
assert.equal(state().storyStage, 2)
for (const id of ENEMY_IDS) assert.equal(state().damageEnemy(id, 999), true)
assert.equal(state().storyStage, 3)
state().interactWithStory()
const core = state().storyTerminals.find((terminal) => terminal.id === 'core-choice')
state().setNearbyTerminal(core)
assert.equal(state().interactWithStory(), true)
assert.equal(state().chooseStoryEnding('liberate'), true)
assert.equal(state().storyEnding.code, 'ENDING // DAWN')

state().returnToProtocolSelect()
state().startProtocol('race')
assert.equal(state().raceStatus, 'countdown')
state().startProtocol('combat')
assert.equal(state().requestAttack(), true)

console.log('Phase 8 gameplay-overhaul, release, and legacy gameplay state-machine smoke test passed.')
